version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.3.0
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - "discovery.type=single-node"      
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.3.0
    ports:
      - '5601:5601'
  logstash:
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    image: logstash:7.3.0
    ports:
      - '5000:5000'
      - '5044:5044'
    depends_on:
      - elasticsearch
    volumes:
      - ./config/docker-logstash.conf:/etc/logstash/conf.d/logstash.conf
  
volumes:
  elasticsearch: {}
